[package]
name = "census"
version = "0.1.1"
authors = ["Michael Lazear <lazear@scripps.edu>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.89", features=["derive"], optional = true }

[dev-dependencies]
serde_json = "1.0"

[features]
serialization = ["serde"]
